apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZkxRck11N3ZqOFV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBM01UWXhOelV5TkRGYUZ3MHpOREEzTVRReE56VTNOREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNsa01JZE1oeURzTEZoQWFRZTNQYnlVdDZ2bUV5bUFlclNIVWd1SjFKS2tCN3BHRldKRGpZREJhdkUKZnRFR0dmZVhYOG15MS9yQ090ZnEvUkMzTjB1SVliaGZ3allaSERMVGcxUGtrWUhRUFpvMVFYZmlPWkRJN3ZocgpaQ25JbXRub0Flbjc2TGx1Q25XYW1Hd2VOMjRmVFdVbTgzelNCZy9CVG5TNXRHMEhQbm5lS3VWRmRxK25WeXFoCi9idWNHVkpqRnV6L0FvUUFVOUQ0ODZxdkNGeG1PZnlHejdUYVZyNVl5Y1VhNVRyMUFLSGlVT01jUHN2YTFUdG8KU2h5bzFoZEU3RDFSS1JPc2MrYk1BNjZ0ZGJ4VTkwSlNRZ3loMlpQT3RuTTQvcGxkd2cyWUR2TnR1REdUQm5sOQpOTU1XQzJ5dXRNK1FOb3ZKQ2hwR3Zxci9vQ0RqQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSTlWYzU3SFhNWG50cVkxMEFVa3JNc3NPSi9EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWIxQXZRTUlKUApRUmpKak13elFMb2g2eU9teE1XbGJ6YkloVldpVDZGWDM0TE4rL1Fpei9iQVdtZERhbVBaOEdmbDlYdjBMWUhMCktiY3l1cXR2V0szbytDdWh1Qk1nTXVkdUFTR01HaHNBR01hQXU1UHJudFhQcWN5emhkQU5WK1pIMmp2MUorSVkKUDlHM3RBY0tXMWFsb081dGt2dkpYZnQ4aFJPVVlQK0xjYXlLczJUdElMbzVxNmJ1Y1JSTE1YOFo4dGU0RDV3QQpaeTcwd2c0Zk1FYXlpRVVQUG9sbUFGNUgxZ3pZMlRuWnVzN3h4dFBLTDMyQzFSeFlBQ21TNy9WVW52TitCWHo0Cm9ndFcrZmgrclN4YmRKdVZWMzJ0S1lSWHZjc2o0UW5EcVZrZTk2NHBlYWJRYnUrRVRBcDZkeXMyR3UrM2pwRUEKN25XQ3NuUy9icTkyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://98D0C19100BE66A407D31E1FD4F31E91.gr7.us-east-1.eks.amazonaws.com
  name: demo-cluster.us-east-1.eksctl.io
contexts:
- context:
    cluster: demo-cluster.us-east-1.eksctl.io
    user: admin@demo-cluster.us-east-1.eksctl.io
  name: admin@demo-cluster.us-east-1.eksctl.io
current-context: admin@demo-cluster.us-east-1.eksctl.io
kind: Config
preferences: {}
users:
- name: admin@demo-cluster.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - demo-cluster
      - --region
      - us-east-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
